name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts-name}}
      - name: Output Information
        run: echo "Running and deploying"